chore(deps): Bump vendor/libatomic_ops from `20390d7` to `57a19a8` (#303)
Bumps [vendor/libatomic_ops](https://github.com/ivmai/libatomic_ops)
from `20390d7` to `57a19a8`.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/57a19a876a525145963f3900c3f49ae224dcfc62"><code>57a19a8</code></a>
Fix GH Actions badge name in README</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/1462cfc2ee0441dc51522578318a8ecbf6a88507"><code>1462cfc</code></a>
GH Actions: Turn on verbose build mode and fail on compiler
warnings</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/fc422be8d6f05153ccc3715641f12202b5e0b404"><code>fc422be</code></a>
GH Actions: Rename config file to match workflow name</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/ccb9e55066758ca177cf55622ad5ddc756da5ec6"><code>ccb9e55</code></a>
GH Actions: Fix builds on Windows by clang and gcc</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/3f26dfaeb2179332edd96c6f96a09fa28f509cdd"><code>3f26dfa</code></a>
GH Actions: Remove non-working architectures (other than amd64)</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/3b67edfea610b2a94ab459293d9dd45345cf1b70"><code>3b67edf</code></a>
Fix 'undefined reference to __atomic_load/store/cas_16' Mingw64-gcc
error</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/3b5a38599f15e961a309f39cf137d93ec2dc27ff"><code>3b5a385</code></a>
GH Actions: change workflow name to 'cmake build'</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/731159d0f20231003ba2d847b24982250b169a89"><code>731159d</code></a>
Remove total-lines badge from README</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/b20dfa8f8a7b24cb7b95f963463e42ab29b3c50a"><code>b20dfa8</code></a>
Add GH Actions build status badge to README</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/ae0d836001aa19a61d99ea9cf714ff22c9ddd308"><code>ae0d836</code></a>
GH Actions: initial setup of build and test using CMake</li>
<li>Additional commits viewable in <a
href="https://github.com/ivmai/libatomic_ops/compare/20390d751cfb995e5fe3f7b3e79c61806f57bff8...57a19a876a525145963f3900c3f49ae224dcfc62">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>