chore(deps): Bump vendor/libatomic_ops from `e06dc95` to `7244051` (#258)
Bumps [vendor/libatomic_ops](https://github.com/ivmai/libatomic_ops)
from `e06dc95` to `7244051`.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/724405171d08abb56ae391a85fca20088c189761"><code>7244051</code></a>
Travis CI: Test -D AO_USE_PTHREAD_DEFS on Ubuntu Jammy</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/340d74e570714b67fbee9d145c7f056730f4399d"><code>340d74e</code></a>
Fix 'undefined reference to AO_pt_lock' if configure is using
clang-16</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/3e53e2656277f77076707383a767a78f1cb0c5cb"><code>3e53e26</code></a>
Travis CI: Use Jammy for most Ubuntu builds</li>
<li><a
href="https://github.com/ivmai/libatomic_ops/commit/09d68d8e7179b9dc0d97d79822ee972a3b6b8fa6"><code>09d68d8</code></a>
Travis CI: Make all configurations unique regardless of dist</li>
<li>See full diff in <a
href="https://github.com/ivmai/libatomic_ops/compare/e06dc9549f1c24f8564501a9c5a264d20af1c4b5...724405171d08abb56ae391a85fca20088c189761">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>